fluree/db

- .dockerignore
- Dockerfile
- Makefile
- build-browser.edn
- deps.edn
- src/fluree/db/token_auth.cljc
I didn't test this super thoroughly, but it does at least compile now and I get the "FlureeDB APIs v0.17.0" message in the browser's JS console when I load up the compiled JS.
> Fix browser cljs build

- src/fluree/db/api/ledger.cljc
update ledger/db to use try*catch* macro for nodejs (ClojureScript) use
> FC-918 update ledger/db to use try*/catch* macro

- src/fluree/db/auth.cljc
Updated roles to also accept a string auth
> FC-786 update to accept string auth

- .github/workflows/ci.yml
- Dockerfile
- Makefile
- docker-chrome-seccomp.json
- script/run-in-docker.sh
- test-build.edn
Now that we have some tests, we should run 'em!
I made a ticket for this: FC-1001
> Run tests in CI pipeline

- src/fluree/db/class/core.cljc
- src/fluree/db/query/range.cljc
- test/fluree/db/query/sql_test.cljc
Feel free to ignore the first commit. Just some formatting cleanups.
The second "Use if-some" commit is the real change. I'm not positive this is the full fix for the bool query issues we're seeing, but it does seem strictly better than what was there before.
> Fix boolean queries

- src/fluree/db/query/fql.cljc
This is a "quick-fix" for a client-reported issue - more refactoring is needed; but, will be tracked under FC-1048.. comments welcome!
* changed process to 1) get-results, 2) apply sort (if orderBy), 3) apply limit/offset during sort when no groupBy, selectDistinct 4) format/expand results and then 5) if selectDistinct?, apply limit/offset
* changed commands used to selectDistinct to retain sort order
* fixed spelling in error message
> FC-1057 fix for selectDistinct, offset, limit

- src/fluree/db/query/fql.cljc
Fixing a couple of scenarios:
- "invalid" orderBy, in that the variable/predicate is not found in the where clause, apply offset/limit to results.  
- no orderBy or groupBy, apply offset/limit to results
--- Note ---
There is an outstanding refactor ticket for the variations of orderBy, groupBy, offset & limit.  We may want to consider building out the result set before applying the orderBy so that any data point available in the "select" can be used for the orderBy.
> FC-1056 apply offset/limit when no orderBy or groupBy specified

- src/fluree/db/query/fql.cljc
This solves the issue of some more complex queries that have :limit or :offset doing a lot of extra work.
> FC-1048 Some queries not filtering work for limit/offset conditions

- src/fluree/db/query/analytical.cljc
Merging multiple tuple sets was inefficient, this helps quite a bit.
> FC-1048 Refactor tuple merging function in analytical queries

- src/fluree/db/query/fql.cljc
Select maps in analytical queries will now process with a defined parallelism (set to 8 currently)
> FC-1048 Process select maps in analytical queries in parallel

- src/fluree/db/query/fql.cljc
selectDistinct with :limit performed the :limit before distinct - resulting in the possibility of fewer results returned than specified in :limit. 
The general logic for the final processing of results from the `where` clause to conforming to the `select` clause was spread out and duplicated. Migrated this pipeline to use one transducer composition path.
> Addresses both FC-1094 and FC-1095 selectDistinct bug and transducer pipeline

- src/fluree/db/query/fql.cljc
Fixed reported issue: 
When a predicate is :component it doesn't get its predicate names shortened in query results on a :compact query
> FC-1080 fix issue where :compact? was dropped when following components

- src/fluree/db/api.clj
Fixed issue where an async channel was returned versus results.  
Also added a go-try block to catch & return errors.
Reported issue:
FC-1110 /transact doesn't return immediate 400 for too-large transactions if the transaction includes a password API bearer token
> FC-1110 fix issue where async channel returned; added go-try wrapper

- src/fluree/db/memorydb.cljc
This adds basic capability as per FC-1148
> FC-1148 Add basic local, in-memory db

- .clj-kondo/ci-config.edn
- .clj-kondo/config.edn
- .gitignore
- deps.edn
Added commands for clj-kondo, cloverage, eastwood, and liquid/antq.
> FC-1154 add cmds for various linters

- src/fluree/db/dbfunctions/core.cljc
Related to https://github.com/fluree/ledger/pull/60
> FC-1178: Local/built-in functions lookup done without async chans

- deps.edn
- package.json
Updated dependencies, including packages for CI/CD test
> FC-1185 Update dependencies

- src/fluree/db/spec.cljc
- test/fluree/db/spec_test.cljc
Added support for string -> float conversion, just like double. 
Also added a unit test for double/float.
> FC-1204 Fix/float parse error

- src/fluree/db/query/fql.cljc
If you issue limit: 1, 2 results will return. Only affects legacy basic queries that contain the string :where clause.
> FC-1261 - legacy where string query limit off by 1 result

- src/fluree/db/query/fql.cljc
Legacy string where query AND condition not working properly
> FC-1267 Fix string-based where query with AND condition

- src/fluree/db/query/analytical.cljc
- src/fluree/db/query/fql.cljc
Permissioned graph crawls could leak out 'nil' values where permission to see the data is not allowed. Instead of nil values, the predicate shouldn't even be listed acknowledging as to not acknowledge its existence.
News tests have been added in fluree/ledger to test this behavior
> FC-1254, FC-1270 Fix/permissioned crawls

- src/fluree/db/connection.cljc
> Add :keep-alive-fn support to clojure api

- src/fluree/db/util/async.cljc
Throws any exceptions coming off of the channel it takes from
Part of the fix for FC-1338
> FC-1338 - Add util.async/alts?? fn

- src/fluree/db/api.clj
There was some string vs. keyword confusion happening
Companion PR to https://github.com/fluree/ledger/pull/128
> Fix ledger-ready? fns in api

- src/fluree/db/api/query.cljc
- src/fluree/db/dbfunctions/internal.cljc
- src/fluree/db/full_text.clj
- src/fluree/db/permissions_validate.cljc
- src/fluree/db/query/block.cljc
- src/fluree/db/query/fql.cljc
- src/fluree/db/query/range.cljc
- src/fluree/db/query/schema.cljc
- src/fluree/db/session.cljc
- src/fluree/db/storage/core.cljc
- src/fluree/db/time_travel.cljc
- src/fluree/db/util/pprint.clj
- src/fluree/db/util/schema.cljc
- src/fluree/db/util/tx.clj
Still need to reference the Flake instance in fluree.db.session and fluree.db.util.json.
> Remove obsolete Flake imports and type hints

- Makefile
- script/create-node-package.sh
- script/umd-wrapper.prefix
- script/umd-wrapper.suffix
Copy the files in `out/nodejs/package` to the flureejs repo in `packages/flureenjs/` to
publish.
> Automate flureenjs packaging process

- src/fluree/db/api.clj
- src/fluree/db/constants.cljc
- src/fluree/db/graphdb.cljc
- src/fluree/db/query/http_signatures.cljc
- src/fluree/db/util/async.cljc
- src/fluree/db/util/tx.clj
This is the db portion of allowing HTTP signatures to validate transactions sent to the /transact endpoint.
ledger PR: https://github.com/fluree/ledger/pull/130
JIRA ticket: FC-1355
Merge #146 first!
> FC-1355 - Feature: trust http sigs for transactions

- docs/fluree.db.api.html
- js-packages/nodejs/package.json
- src-cljs/flureedb.cljs
- src-nodejs/flureenjs.cljs
- src/fluree/db/api.clj
- src/fluree/db/api/ledger.cljc
- src/fluree/db/api/query.cljc
- src/fluree/db/api_js.cljs
- src/fluree/db/connection.cljc
- src/fluree/db/dbfunctions/core.cljc
- src/fluree/db/dbfunctions/ctx.cljc
- src/fluree/db/event_bus.cljc
- src/fluree/db/full_text.clj
- src/fluree/db/graphdb.cljc
- src/fluree/db/index.cljc
- src/fluree/db/operations.cljc
- src/fluree/db/performance.clj
- src/fluree/db/permissions.cljc
- src/fluree/db/query/analytical.cljc
- src/fluree/db/query/fql.cljc
- src/fluree/db/query/graphql_parser.cljc
- src/fluree/db/query/range.cljc
- src/fluree/db/serde/avro.clj
- src/fluree/db/session.cljc
- src/fluree/db/storage/core.cljc
Any other cleanups we want in here for 2.0.0-alpha1?
> Remove deprecations & replace db with ledger everywhere appropriate

- src/fluree/db/connection.cljc
If you supply `keep-alive` `true` as a `connect` opt, if the socket server doesn't
respond to two pings then the client will close the socket and try to re-establish it,
with an exponential backoff to two minutes. This allows the client to stay up while the
server is restarted.
FC-3188
> Add keep-alive opt to perpetually retry establishing client conn

- src/fluree/db/dbfunctions/fns.cljc
- src/fluree/db/dbfunctions/internal.cljc
Much nicer to use than `(nth ... 0)` in the many common cases where you know there will only be 1 result from a coll-returning smartfn (or you only care about the first result).
> Add a `first` smartfn

- src/fluree/db/query/analytical_parse.cljc
Fixes a bug where the filter vars weren't being looked for in optional clauses.
> Check optional clause for filter variables

- src/fluree/db/api/query.cljc
- src/fluree/db/json_ld/transact.cljc
- src/fluree/db/query/analytical_parse.cljc
- src/fluree/db/query/compound.cljc
- src/fluree/db/query/subject_crawl/core.cljc
- src/fluree/db/query/subject_crawl/legacy.cljc
- src/fluree/db/query/subject_crawl/reparse.cljc
- test/fluree/db/query/misc_queries_test.clj
- test/fluree/db/transact/delete_test.clj
This addresses #216 and allows for this query to work. Includes a test.
```
@(fluree/query db {:select ['?s '?p '?o]
:where  [['?s '?p '?o]]})
```
> Feature/spo query (issue #216)

- README.md
Updates the README to have the correct instructions for installing babashka.
> Fix instructions for installing babashka

- test/fluree/db/query/history_test.clj
- test/fluree/db/test_utils.cljc
> update new tests to use new commit! arity

- src/fluree/db/permissions_validate.cljc
...and replace docstring snippet in `allow-flake?` to not use it for that.
Not a strict `git revert ...` because I didn't want to restore the obsolete comment in `allow-flakes?` saying we should do this.
> Revert root short-circuit in allow-flake(s)

- deps.edn
These dependencies were no longer used by fluree/db
> Remove unused dependencies

- src/fluree/db/json_ld/shacl.cljc
- test/fluree/db/shacl/shacl_basic_test.clj
Closes #320 
Adds support for:
- `sh:minExclusive`
- `sh:minInclusive`
- `sh:maxExclusive`
- `sh:maxInclusive`
Throws an error if a value either violates the constraint, or is not a numeric type.
> add support for SHACL value range constraints

- src/fluree/db/api/query.cljc
- src/fluree/db/query/fql/syntax.cljc
- src/fluree/db/query/history.cljc
- src/fluree/db/util/core.cljc
- src/fluree/db/util/validation.cljc
- test/fluree/db/query/history_test.clj
- test/fluree/db/query/misc_queries_test.clj
The db side of fixing coercion of multi-query opts in JSON + correct handling of @whatever JSON-LD keywords.
Counterpart to https://github.com/fluree/http-api-gateway/pull/52 which fixes https://github.com/fluree/http-api-gateway/issues/50.
> Fix query key decoding

- src/fluree/db/query/fql.cljc
...b/c groupBy & orderBy are on different values, for example.
Fixes #478
> Order each group of results when needed

- Makefile
- dev/logback-test.xml
- src/fluree/db/json_ld/shacl.cljc
- test/fluree/db/shacl/shacl_basic_test.clj
> Feature: shacl `in` property

- src/fluree/db/json_ld/reify.cljc
There were some structural changes to what commit json-ld looks like, this changes the loading process to account for that new structure.
> fix commit loading to account for proper json-ld structure

- src/fluree/db/query/exec/select.cljc
- src/fluree/db/query/fql/parse.cljc
- src/fluree/db/query/fql/syntax.cljc
- src/fluree/db/query/json_ld/select.cljc
- src/fluree/db/validation.cljc
- test/fluree/db/query/fql_test.clj
- test/fluree/db/query/sparql_test.cljc
Implements this in both SPARQL & FQL.
Closes #510
Closes #511
> Feature: SPARQL SELECT * w/o graph crawl

- deps.edn
- test/fluree/db/json_ld/api_test.cljc
This updates the json-ld dep and changes the usage to match.
Depends on https://github.com/fluree/json-ld/pull/27
> update fluree context iri

- test/nodejs/flureenjs.test.js
Part of my work on https://github.com/fluree/core/issues/40
> Fix test formatting and update some commented-out code

- .github/workflows/ci.yml
...to hopefully cut down on "too many requests" errors
> Login to Docker Hub in CI

- test/fluree/db/query/fql_test.clj
> Fix code formatting in f.d.q.fql-test

- test/fluree/db/query/fql_test.clj
This introduces a new ^:pending test metadata that we should filter out
of regular test runs if we end up adopting it. I may introduce that in a
subsequent PR. If nothing ever comes of that, feel free to remove it.
Part of my work on #576
> Add a pending test for the datatype query fn

- deps.edn
- src/fluree/db/query/exec/eval.cljc
Just something I noticed while working on #576
> Remove redundant starting value in a sum reduce

- src/fluree/db/api/transact.cljc
- src/fluree/db/json_ld/transact.cljc
- src/fluree/db/query/fql/parse.cljc
- src/fluree/db/query/fql/syntax.cljc
- src/fluree/db/query/history.cljc
- src/fluree/db/validation.cljc
Clean up some minor formatting & similar issues
Clean up some minor formatting & similar issues
> Clean up some minor formatting & similar issues

- src/fluree/db/query/sparql2fql.cljc
- test/fluree/db/query/sparql_test.cljc
May not be the most efficient output, but we want to
move this away from generating FQL (and use our
internal format instead) anyway.
> Update SPARQL->FQL code to generate new query syntax

- src/fluree/db/json_ld/transact.cljc
- src/fluree/db/query/exec/update.cljc
- src/fluree/db/query/exec/where.cljc
- src/fluree/db/query/fql/parse.cljc
- test/fluree/db/json_ld/api_test.cljc
- test/fluree/db/transact/transact_test.clj
This will ensure that insert and delete clauses are processed at least once, regardless of the results of evaluating the where clause.
Fixes https://github.com/fluree/core/issues/46
> ensure at least one solution is provided to the update pipeline

- test/fluree/db/transact/update_test.clj
Should be all whitespace changes
> Format code in f.d.transact.update-test

- test/fluree/db/transact/update_test.clj
From https://github.com/fluree/core/issues/49
> Add a pending test for a failing txn

- src/fluree/db/conn/core.cljc
- src/fluree/db/ledger/json_ld.cljc
This adds extra logging condition for calls to fluree/notify, and also will log out if supplied map doesn't look like a commit map to alert the user.
> Add extra condition and logging for fluree/notify

- src/fluree/db/json_ld/vocab.cljc
- test/fluree/db/query/reverse_query_test.clj
- test/fluree/db/query/subclass_test.clj
Fixes https://github.com/fluree/core/issues/48
> Fix subclassOf inferencing

- src/fluree/db/query/exec/update.cljc
- src/fluree/db/query/fql/parse.cljc
- test/fluree/db/query/property_test.clj
- test/fluree/db/transact/transact_test.clj
> Fix vars in o position in txns

- test/fluree/db/query/json_ld_basic_test.clj
Bug report but it was already fixed. I figured the test was a good addition against any regressions.
> Add a test for queries w/ faux compact IRI

- dev/ipfs_demo.clj
- src/fluree/db/conn/ipfs.cljc
- src/fluree/db/method/ipfs/core.cljc
- src/fluree/db/nameservice/ipns.cljc
This fixes the IPFS/IPNS support that was broken in the Nameservice changes that previously happened.
> Fixes IPFS / IPNS Nameservice support

- src/fluree/db/conn/file.cljc
- src/fluree/db/conn/memory.cljc
- src/fluree/db/conn/s3.clj
- src/fluree/db/json_ld/api.cljc
- src/fluree/db/storage.cljc
- src/fluree/db/storage/s3.clj
This converts the s3 connection to use the s3 store abstraction.
> convert s3 conn to use s3 store

- dev/user.clj
This leverages the syntax updates we've had recently to update this namespace.
> Update dev user namespace with latest syntax

- README.md
Add installation instructions for prerequisites for windows machine
> Update readme for windows

- src/clj/fluree/db/json_ld/vocab.cljc
- test/fluree/db/query/subclass_test.clj
The :schema map generation changed, and no longer worked correctly for rdfs:subClassOf processing.
This adds a test that would fail prior to this patch, but succeeds with it.
The issue originated from any db change generating a new :schema map, then later merging it with the prior one. The issue is with at least rdfs:subClassOf, there can be dependencies on the prior schema map.
This now carries the current schema map through instead of re-generating it with every update and later merging it. The merge is no longer necessary as the new map is based on the old.
> Fix :schema map generation

- src/clj/fluree/db/api/query.cljc
> Revert "Include reasoning logic when restricting db"

- src/clj/fluree/db/json_ld/credential.cljc
- test/fluree/db/json_ld/credential_test.cljc
Add error message status code to crypto verification exceptions
> Add status codes to crypto/credential failures

- test/fluree/db/policy/query_test.clj
This adds a new policy test focused onClass restriction only with default allow? of both true and false.
@aaj3f I believe this tests for the scenario you brought up and it appears to work correctly. Would be great if you could confirm, and then likely the issue is something specific to fluree/server and I'll look there provided this is correct.
> Add additional policy test

- src/clj/fluree/db/query/sparql/translator.cljc
- test/fluree/db/query/sparql_test.cljc
A quick fix for string and iris in expressions.
> quote string literals in code expressions

- src/clj/fluree/db/async_db.cljc
- src/clj/fluree/db/json_ld/policy.cljc
This fixes the error Andrew was seeing when trying to query with an identity policy in place after a server restart.
> add IFlureeDb/-query impl for AsyncDB

- src/clj/fluree/db/api.cljc
- src/clj/fluree/db/json_ld/policy.cljc
This addresses remaining API issues that stemmed from the changes in #900 and also relates to #909
> Other fixes based on the kebab-case API parsing

- src/clj/fluree/db/api/transact.cljc
- src/clj/fluree/db/flake/flake_db.cljc
- src/clj/fluree/db/flake/index/novelty.cljc
- src/clj/fluree/db/flake/transact.cljc
- src/clj/fluree/db/query/fql/syntax.cljc
- test/fluree/db_test.cljc
Fixes https://github.com/fluree/core/issues/130
> add support for backpressure when novelty-max-bytes is exceeded

- test/fluree/db_test.cljc
Fix typo in test case. Please see https://en.wikipedia.org/wiki/Star_Wars_opening_crawl for reference :)
> CHORE: Fix typo in test

- src/clj/fluree/db/flake/index.cljc
- test/fluree/db/query/misc_queries_test.clj
There are two reasons a flake can be "stale":
1. The flake has been retracted
2. An identical flake was added in a later transaction
When the `remove-stale-flakes` function was refactored for performance, only stale flakes in the first sense were removed.
In the second sense, we check if flakes are semantically identical by comparing the values: s, p, o, dt, m. However, our sorted sets also take into consideration `t`, so two flakes with same semantic content but with different t values can coexist in our indexes.
This change adds back support for the second sense of "stale" and attempts to preserve as much of the performance boost as possible by reusing the transient flakes set.
> remove "duplicate" flakes when scanning an index

- src/clj/fluree/db/indexer/garbage.cljc
When cleaning garbage, the logging shows inaccurate garbage cleaning reports and with 'nil' values reported and inaccurate garbage collection counts.
This is because the oldest index root file will point to an even older garbage file which was already cleaned by the prior garbage collection. This is not the case in the first run of garbage collection, but only subsequent runs.
Not only is the count wrong, but the logging reports the data being removed for each garbage file - and when the file is gone, it reports a number of 'nil' values - which appears there is some sort of system error.
This now checks the oldest garbage file(s) for existence before reporting the garbage collection count so reporting is accurate.
> Improve accuracy of garbage reporting/exceptions

- src/clj/fluree/db/query/sparql/translator.cljc
- test/fluree/db/query/sparql_test.cljc
Add support for boolean literals in SPARQL queries.
> add support for boolean literals in SPARQL queries

- src/fluree/db/virtual_graph/flat_rank.cljc
I noticed we don't track fuel for vector searches, so I added support for that as well.
> add fuel tracking to virtual graph search

- src/fluree/db/query/api.cljc
Compiling the policies to restrict a db requires executing queries, which requires tracking fuel usage. This moves fuel tracker creation to the beginning of the pipeline.
> create fuel tracker before any fuel is spent

- src/fluree/db/virtual_graph/bm25/update.clj
This fixes an issue where a multi-cardinality string in the bm25 index can create an issue.
The problem was a syntax error, no changes in logic.
Closes https://github.com/fluree/core/issues/182
> Fix bm25 multi-cardinality strings issue

- src/fluree/db/flake/flake_db.cljc
Small change to speed up commits a little (at least larger commits)
> speed up commits with transient

- src/fluree/db/query/sparql.cljc
- test/fluree/db/query/sparql_test.cljc
Closes https://github.com/fluree/core/issues/185
> add descriptive parse errors for sparql

- src/fluree/db/track/fuel.cljc
This patch simplifies and dramatically optimizes fuel tracking by using a single atom to track the total fuel used for a query or transaction instead of keeping track of an atom of volatiles for each parallel thread of execution. 
We initially chose to use the atom of volatiles to avoid the contention of using a single atom shared across multiple parallel execution threads.  However this later created a tradeoff with the additional requirement of adding fuel limits and short circuiting the computation when that is exceeded. This required that all the volatiles be constantly summed to keep track of the current global fuel total to decide if we need to short-circuit the computation. The constant repeated summing of the distinct volatiles has much worse computational complexity than the …
> use a single atom to manage fuel

- src/fluree/db/api.cljc
- src/fluree/db/connection/system.cljc
- src/fluree/db/connection/vocab.cljc
- src/fluree/db/storage/s3.clj
- test/fluree/db/storage/s3_testcontainers_test.clj
storage/s3: add configurable timeouts and retries; wire config; update LocalStack tests
> storage/s3: add configurable timeouts and retries; wire config; update LocalStack tests; fix lints

- src/fluree/db/json_ld/shacl.cljc
- test/fluree/db/shacl/shacl_basic_test.clj
We were trying to compare all values with `<`, `<=`, time values need to use `compare`.
> add time support for shacl lessThan, lessThanOrEqual constraints
